# Generated by Django 6.0 on 2025-12-28 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeArrosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Groupe d'arrosage",
                'verbose_name_plural': "Groupes d'arrosage",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Arrosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('latitude_debut', models.FloatField()),
                ('longitude_debut', models.FloatField()),
                ('latitude_fin', models.FloatField(blank=True, null=True)),
                ('longitude_fin', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('invalide', 'Invalidé')], default='en_cours', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrosages', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrosages', to='pointage.groupearrosage')),
            ],
            options={
                'verbose_name': 'Arrosage',
                'verbose_name_plural': 'Arrosages',
                'ordering': ['-heure_debut'],
            },
        ),
    ]
